### ISSUE TITLE
Add support for Pinecone programs to get command line args

### ISSUE THREAD

**Issue by olegispe** [william01110111/Pinecone#12]
I've seen a previous commit that allowed command line argument support, but how do I use these arguments in a program?

**Comment by william01110111** [comment]
That commit was for controlling the interpreter with arguments there is currently not support for giving your program arguments. I will update this issue when I implement this.

**Comment by olegispe** [comment]
ok, i will be sure to check by later

**Comment by olegispe** [comment]
I'll try and add this myself soon. If you want.

**Comment by william01110111** [comment]
Go for it. Sorry I haven't added it, I haven't worked on Pinecone much lately.

**Comment by william01110111** [comment]
on lines 193 and 227 in src/main.cpp I set i (the current command line arg being processed) to argc (the cont of the arguments. To implement command line args, make a vector of strings in the Flags struct (in main.cpp), fill that with all the arguments that come after the -e or -r flag and then expose that as a builtin global variable.

**Comment by william01110111** [comment]
On second thought, you might want to make the args vector a global, so you can access it in PineconeStdLib.cpp where you can expose it. If you have any trouble implementing it, let me know.

**Comment by olegispe** [comment]
Currently out, when I get home I'll implement that and then merge.

**Comment by olegispe** [comment]
i haven't used c++ in a while.

But i gave it a go, from what i can remember.

[here](https://github.com/olegispe/Pinecone/tree/patch-2)

**Comment by olegispe** [comment]
It is very much a **WIP** change.

You're probably better to do it, you know in better detail how you want it to work.

**Comment by william01110111** [comment]
Your patch looks good but still needs some stuff I will add (as per my comment on the PR)

Also, a different system needs to be created for argument parsing when transpiled. For starters, when transpiling and automatically running the arguments after the -e must be carried along to the executed binary. This can be done by using [this](https://github.com/william01110111/Pinecone/blob/master/h/utils/stringArray.h#L19) function on your args vector and appending it to the executed command around [here](https://github.com/william01110111/Pinecone/blob/master/src/main.cpp#L142). You can do that on your patch branch if you want. There is other stuff that's needed in the transpiled code, but that's a bit complicated. I'll look into it later.

**Comment by william01110111** [comment]
Merged in your PR with my additions and fixes. It now supports command line args both when compiled or interpreted. Documentation for this feature is at the end of the temporary hacks tutorial.
