### ISSUE TITLE
Probably a big ask: linking with C/C++ libraries

### ISSUE THREAD

**Issue by alexbuzzbee** [william01110111/Pinecone#14]
Pinecone does not currently support linking with C/C++ libraries. One example is `ncurses`, which provides screen manipulation support. If we could use that, we could rewrite `snake` yet again, adding yet more :star:*gameplay features*:star:.

I understand that this is a *very* complicated feature in an interpreted language (heck, Python hasn't got it fully figured out), but it would be very nice not to have to constantly re-invent the wheel. :)

**Comment by william01110111** [comment]
Since Pinecone transpiles to C++, this is not terribly hard (full explanation [here](https://www.reddit.com/r/PineconeLang/comments/65ai4m/embedding_pinecone_in_c_programs_like_chaiscript/). I plan to do it sooner or later, but I haven't had time to work on Pinecone lately.

**Comment by alexbuzzbee** [comment]
I am surprised that it would be so easy. :)

**Comment by william01110111** [comment]
Simple version done and pushed to master. see bottom of [this tutorial](https://github.com/william01110111/Pinecone/blob/master/tutorials/7_temporary_hacks.md) for details.
